const personalities = [
    "academic",
    "adaptable",
    "adventurous",
    "affectionate",
    "analytical",
    "anxious",
    "artistic",
    "articulate",
    "athletic",
    "authentic",
    "calm",
    "capable",
    "cautious",
    "charming",
    "cheerful",
    "childish",
    "clever",
    "compassionate",
    "complex",
    "confident",
    "contemplative",
    "cooperative",
    "courageous",
    "crazy",
    "creative",
    "curious",
    "cunning",
    "decisive",
    "devoted",
    "diplomatic",
    "dramatic",
    "dutiful",
    "dynamic",
    "earnest",
    "eccentric",
    "educated",
    "efficient",
    "eloquent",
    "empathetic",
    "energetic",
    "engaging",
    "enigmatic",
    "enthusiastic",
    "ethical",
    "extravagant",
    "fair",
    "faithful",
    "family-oriented",
    "feminine",
    "fierce",
    "foolish",
    "forgiving",
    "friendly",
    "fun-loving",
    "geeky",
    "generous",
    "gentle",
    "giving",
    "gracious",
    "gregarious",
    "grounded",
    "guarded",
    "helpful",
    "hopeful",
    "humble",
    "hyped",
    "hyperactive",
    "idealistic",
    "imaginative",
    "impulsive",
    "independent",
    "industrious",
    "innocent",
    "insightful",
    "intelligent",
    "intense",
    "intuitive",
    "inventive",
    "joyful",
    "keen",
    "kind",
    "knowledgeable",
    "laid-back",
    "level-headed",
    "liar",
    "lively",
    "logical",
    "loving",
    "loyal",
    "masculine",
    "mature",
    "methodical",
    "meticulous",
    "mindful",
    "modest",
    "musical",
    "neat",
    "nerd",
    "noble",
    "nurturing",
    "obedient",
    "observant",
    "open-minded",
    "optimistic",
    "orderly",
    "outgoing",
    "parent",
    "partner",
    "patient",
    "peaceful",
    "pensive",
    "perceptive",
    "perfectionist",
    "perseverant",
    "persuasive",
    "philosophical",
    "plainspoken",
    "playful",
    "poised",
    "polite",
    "positive",
    "pragmatic",
    "precise",
    "principled",
    "proactive",
    "professional",
    "protective",
    "prudent",
    "punctual",
    "pure",
    "quiet",
    "quirky",
    "rational",
    "realistic",
    "rebellious",
    "reflective",
    "reliable",
    "resilient",
    "resourceful",
    "respectful",
    "responsible",
    "restrained",
    "reverent",
    "romantic",
    "sarcastic",
    "scholarly",
    "scientific",
    "self-assured",
    "self-disciplined",
    "selfless",
    "sensitive",
    "sentimental",
    "serious",
    "shrewd",
    "silly",
    "sincere",
    "skillful",
    "smart",
    "sociable",
    "sophisticated",
    "spiritual",
    "spontaneous",
    "steady",
    "stoic",
    "strong-willed",
    "studious",
    "stupid",
    "suave",
    "submissive",
    "supportive",
    "sweet",
    "sympathetic",
    "systematic",
    "technical",
    "tenderhearted",
    "thorough",
    "tidy",
    "tolerant",
    "tough",
    "traditional",
    "trickster",
    "trusting",
    "unassuming",
    "understanding",
    "unflappable",
    "unique",
    "unpredictable",
    "unpretentious",
    "upbeat",
    "urbane",
    "versatile",
    "vigilant",
    "vivacious",
    "warmhearted",
    "whimsical",
    "wise",
    "witty",
    "youthful",
    "zany",
    "zealous",
    //[NSFW]
    "*abuser",
    "*addict",
    "*alcoholic",
    "*asexual",
    "*cheating",
    "*coquettish",
    "*debauched",
    "*depressed",
    "*desirous",
    "*desirable",
    "*dominant",
    "*dominatrix",
    "*easy",
    "*exhibitionist",
    "*fetishist",
    "*flirtatious",
    "*intimate",
    "*killer",
    "*lover",
    "*lustful",
    "*masochistic",
    "*nudist",
    "*nymph",
    "*nymphomaniac",
    "*pain seeker",
    "*polyamorous",
    "*predator",
    "*prostitute",
    "*provocative",
    "*psychopath",
    "*racist",
    "*sadistic",
    "*satyr",
    "*seductive",
    "*sensualist",
    "*sexoholic",
    "*sexual",
    "*slave",
    "*slut",
    "*submissive",
    "*swinger",
    "*temptress",
    "*transgressive",
    "*unfaithful",
    "*victim",
    "*violent",
    "*virgin",
    "*voyeur",
    "*vulgar",
    "*whore"
];

const traits = [
    "Studious, Intellectual, Analytical, Inquisitive, Knowledgeable, Learned, Scholarly, Educated, Bookish, Academic",
    "Flexible, Versatile, Changeable, Pliable, Adjustable, Modifiable, Mutable, Convertible, Malleable, Fluid",
    "Daring, Bold, Brave, Courageous, Intrepid, Audacious, Heroic, Valiant, Dauntless, Fearless",
    "Caring, Loving, Tender, Warm, Intimate, Attachment, Fondness, Devotion, Adoration, Cherishing", 
    "Logical, Systematic, Rational, Reasoned, Measured, Methodical, Calculated, Deliberate, Thoughtful, Investigative",
    "Worried, Troubled, Concerned, Distressed, Uneasy, Restless, Apprehensive, Nervous, Fearful, Tense",
    "Creative, Imaginative, Innovative, Original, Inventive, Talented, Gifted, Inspired, Visionary, Expressive",
    "Eloquent, Well-spoken, Fluent, Expressive, Communicative, Descriptive, Conversant, Linguistic, Silver-tongued, Lucid",
    "Fit, Strong, Coordinated, Agile, Quick, Powerful, Active, Energetic, Vigorous, robust",
    "Genuine, Real, Sincere, Legitimate, True, Veritable, Bona fide, Valid, Actual, Faultless", 
    "Composed, Serene, Tranquil, Peaceful, Unruffled, Collected, Unflustered, Soothing, Placid, Halcyon", 
    "Competent, Qualified, Skilled, Proficient, Talented, Adept, Expert, Accomplished, Resourceful, Handy",
    "Careful, Vigilant, Prudent, Attentive, Wary, Conservative, Guarded, Circumspect, Watchful, Chary",
    "Charismatic, Captivating, Alluring, Appealing, Magnetic, Attractive, Delightful, Enchanting, Engaging, Winsome",
    "Happy, Joyful, Upbeat, Jovial, Merry, Bright, Sunny, Pleasant, Lighthearted, Playful", 
    "Immature, Juvenile, Silly, Foolish, Naive, Innocent, Babyish, Kid-like, Puerile, Infantile",
    "Smart, Brilliant, Quick-witted, Sharp, Ingenious, Canny, Astute, Perceptive, Sagacious, Resourceful",
    "Caring, Kind, Sympathetic, Considerate, Benevolent, Empathetic, Altruistic, Thoughtful, Humane, Selfless",
    "Complicated, Intricate, Involved, Difficult, Perplexing, Entangled, Convoluted, Obscure, Multifaceted, Embroiled",
    "Self-assured, Poised, Assertive, Sure, Positive, Bold, Certain, Resolute, Determined, Convinced",
    "Reflective, Meditative, Pensive, Ruminative, Cogitative, Thoughtful, Contemplating, Deliberative, Pondering, Musing",
    "Helpful, Supportive, Collaborative, Contributory, Assisting, Participatory, Accommodating, Obliging, Agreeable, Willing",
    "Brave, Valiant, Heroic, Intrepid, Daring, Bold, Audacious, Fearless, Plucky, Dauntless",
    "Wild, Mad, Insane, Irrational, Unhinged, Unstable, Manic, Chaotic, Erratic, Outlandish",
    "Inventive, Imaginative, Innovative, Original, Visionary, Inspired, Unconventional, Talented, Artistic, Gifted",
    "Inquisitive, Interested, Eager, Enthusiastic, Fascinated, Informed, Inquiring, Questioning, Exploring, Discovering",
    "Clever, Crafty, Sly, Wily, Shrewd, Artful, Conniving, Scheming, Devious, Manipulative",
    "Determined, Resolute, Firm, Assertive, Decided, Conclusive, Definite, Absolute, Clear-cut, Unwavering",
    "Dedicated, Loyal, Faithful, Committed, Steadfast, Fervent, Die-hard, Passionate, Ardent, Allegiant", 
    "Tactful, Discreet, Polite, Respectful, Discerning, Sensitive, Prudent, Judicious, Subtle, Gradual",
    "Expressive, Theatrical, Flamboyant, Melodramatic, Demonstrative, Passionate, Audacious, Vivacious, Exaggerated, Sensational",
    "Responsible, Obligated, Conscientious, Faithful, Dedicated, Loyal, Committed, Devoted, Attentive, Diligent",
    "Energetic, Lively, Vibrant, Active, Vigorous, Forceful, Zestful, Vital, Animated, Spirited",
    "Sincere, Serious, Dedicated, Zealous, Solemn, Grave, Sober, Somber, Genuine, Fervent",
    "Quirky, Odd, Unconventional, Strange, Peculiar, Idiosyncratic, Offbeat, Bizarre, Outlandish, Erratic",
    "Learned, Knowledgeable, Informed, Scholarly, Academic, Intellectual, Cultured, Literary, Studious, Articulate",
    "Capable, Competent, Productive, Effective, Skillful, Expedient, Proficient, Streamlined, Businesslike, Expert",
    "Well-spoken, Articulate, Expressive, Fluent, Persuasive, Silver-tongued, Compelling, Commanding, Charismatic, Meaningful",
    "Compassionate, Understanding, Sympathetic, Relating, Sensitive, Identifying, Caring, Responsive, Perceptive, Intuitive",
    "Lively, Vigorous, Dynamic, Zealous, Spirited, Active, Animated, Vital, Zestful, Zippy",
    "Charming, Captivating, Interesting, Appealing, Likeable, Enjoyable, Pleasant, Affable, Approachable, Welcoming", 
    "Mysterious, Cryptic, Obscure, Ambiguous, Unclear, Vague, Confusing, Uncertain, Inscrutable, Equivocal",
    "Eager, Excited, Passionate, Fervent, Zealous, Ardent, Avid, Gung ho, Keen, Motivated",
    "Moral, Principled, Upright, Honorable, Conscientious, Just, Scrupulous, Righteous, Virtuous, Integrity",
    "Lavish, Ornate, Opulent, Luxurious, Flamboyant, Immoderate, Profligate, Grandiose, Ostentatious, Splendid",
    "Impartial, Even-handed, Reasonable, Open-minded, Equitable, Balanced, Objective, Candid, Unbiased, Neutral",
    "Loyal, Trustworthy, Reliable, Devoted, Dedicated, Steadfast, Allegiant, Constant, True, Dutiful",
    "Domestic, Home-loving, Traditional, Conservative, Committed, Devoted, Marriage-minded, Close-knit, Loyal, Cherishing",
    "Graceful, Sensitive, Soft, Gentle, Tender, Intuitive, Compassionate, Nurturing, Delicate, Empathetic", 
    "Intense, Ferocious, Fearsome, Savage, Formidable, Violent, Forceful, Vicious, Wild, Unrelenting",
    "Silly, Absurd, Ridiculous, Preposterous, Irrational, Dumb, Imprudent, Unwise, Sensless, Nonsensical",
    "Compassionate, Merciful, Lenient, Tolerant, Patient, Clement, Understanding, Accommodating, Charitable, Magnanimous",
    "Outgoing, Sociable, Congenial, Cordial, Warm, Approachable, Affable, Gracious, Neighbourly, Welcoming",
    "Playful, Happy, Carefree, Spirited, Lighthearted, Merry, Jovial, Cheerful, Lively, Mirthful",
    "Nerdy, Intellectual, Bookish, Academic, Scientific, Technical, Brainy, Intelligent, Studious, Knowledgeable",
    "Benevolent, Charitable, Altruistic, Humanitarian, Noble, Magnanimous, Munificent, Lavish, Bountiful, Open-handed",
    "Mild, Kind, Tender, Soft, Meek, Docile, Benevolent, Calm, Tranquil, Compassionate",
    "Generous, Caring, Charitable, Altruistic, Selfless, Benevolent, Philanthropic, Unselfish, Donating, Contributing",
    "Kind, Benevolent, Cordial, Polite, Hospitable, Charitable, Merciful, Courteous, Munificent, Magnanimous",
    "Sociable, Extraverted, Convivial, Friendly, Outgoing, Affable, Amiable, Lively, Boisterous, Garrulous",
    "Practical, Realistic, Stable, Reasonable, Down-to-earth, Level-headed, Commonsensical, Matter-of-fact, Pragmatic, Solid",
    "Cautious, Wary, Careful, Prudent, Circumspect, Judicious, Alert, Watchful, Vigilant, Attentive",
    "Useful, Supportive, Cooperative, Assisting, Accommodating, Handy, Instrumental, Advantageous, Constructive, Beneficial",
    "Optimistic, Confident, Positive, Upbeat, Aspirational, Promising, Bright, Rosy, Cheerful, Future-oriented",
    "Modest, Unassuming, Meek, Self-effacing, Unpretentious, Deferential, Unobtrusive, Docile, Retiring, Unboastful",
    "Brisk, Pumped, Excited, Enthusiastic, Eager, Animated, Electrified, Revved up, Activated, Amped",
    "Energetic, Restless, Antsy, Jumpy, Fidgety, Excitable, Erratic, Frenetic, Impulsive, Exuberant", 
    "Visionary, Utopian, Quixotic, Romantic, Dreamy, Aspiring, Impractical, Theoretical, Perfectionist, Principled",
    "Creative, Inventive, Innovative, Original, Resourceful, Visionary, Ingenious, Clever, Artistic, Talented",
    "Spontaneous, Hasty, Reckless, Unrestrained, Impetuous, Rash, Unthinking, Inconsiderate, Compulsive, Imprudent",
    "Self-reliant, Self-sufficient, Autonomous, Freethinking, Self-governing, Individualistic, Unconstrained, Emancipated, Detached, Free-spirited",
    "Hardworking, Diligent, Dedicated, Assiduous, Sedulous, Conscientious, Productive, Untiring, Tireless, Committed",
    "Naive, Ingenuous, Guileless, Pure, Wholesome, Simple, Uncorrupted, Virtuous, Blameless, Innocuous",
    "Perceptive, Intuitive, Discerning, Astute, Sagacious, Shrewd, Judicious, Penetrating, Thoughtful, Incisive",
    "Brilliant, Gifted, Smart, Sharp, Knowledgeable, Clever, Quick-witted, Rational, Logical, Brainy",
    "Extreme, Passionate, Fierce, Vehement, Powerful, Profound, Acute, Ardent, Fervent, Impassioned",
    "Instinctive, Automatic, Spontaneous, Natural, Subconscious, Sensitive, Prophetic, Psychic, Extrasensory, Clairvoyant",
    "Creative, Innovative, Imaginative, Original, Pioneering, Resourceful, Visionary, Ingenious, Enterprising, Unconventional",
    "Happy, Jubilant, Cheerful, Ecstatic, Blissful, Jovial, Elated, Rapturous, Mirthful, Gleeful",
    "Eager, Enthusiastic, Earnest, Ardent, Fervent, Avid, Excited, Zealous, Passionate, Motivated",
    "Caring, Compassionate, Generous, Benevolent, Gracious, Polite, Thoughtful, Cordial, Warmhearted, Helpful",
    "Well-informed, Educated, Experienced, Learned, Worldly, Informed, Aware, Knowledgeable, Enlightened, Erudite",
    "Relaxed, Easygoing, Calm, Unflappable, Mellow, Casual, Placid, Cool, Nonchalant, Carefree",
    "Rational, Reasonable, Logical, Sensible, Sober, Practical, Prudent, Balanced, Down-to-earth, Composed",
    "Dishonest, Untruthful, Deceitful, Unreliable, Misleading, Fraudulent, Double-dealing, Two-faced, Treacherous, Deceptive",
    "Energetic, Vivacious, Dynamic, animated, Playful, Cheerful, Bubbly, Exuberant, Zestful, Spirited",
    "Rational, Reasonable, Sensible, Analytical, Coherent, Consistent, Orderly, Methodical, Systematic, Sequential",
    "Affectionate, Caring, Warm, Tender, Compassionate, Romantic, Passionate, Cherishing, Devoted, Attached",
    "Faithful, Trustworthy, Allegiant, True, Reliable, Staunch, Devoted, Dedicated, Steadfast, Constant",
    "Strong, Tough, Assertive, Powerful, Authoritative, Protective, Confident, Robust, Forceful, Fearless",
    "Responsible, Grown-up, Worldy, Experienced, Seasoned, Adult, Accomplished, Developed, Sophisticated, Grounded",
    "Systematic, Ordered, Regimented, Logical, Planned, Organized, Structured, Programmed, Step-by-step, Sequential",
    "Precise, Thorough, Perfect, Conscientious, Accurate, Careful, Scrupulous, Attentive, Diligent, Painstaking",
    "Conscious, Present, Aware, Alert, Attentive, Observant, Thoughtful, Regardful, Heedful, Vigilant",
    "Humble, Unpretentious, Unassuming, Meek, Reserved, Shy, Plain, Simple, Unobtrusive, Demure",
    "Melodic, Harmonious, Rhythmic, Lyrical, Tuneful, Soulful, Symphonic, Operatic, Orchestral, Choral",
    "Orderly, Organized, Methodical, Tidy, Systematic, Arranged, Composed, Uncluttered, Unmessy, Structured",
    "Intelligent, Bookish, Studious, Academic, Scientific, Technical, Intellectual, Brainy, Knowledgeable, Precise",
    "Honorable, Dignified, Exalted, Distinguished, Upright, Virtuous, Principled, Ethical, Highborn, Lordly",
    "Caring, Loving, Supportive, Protective, Compassionate, Benevolent, Parental, Helpful, Tender, Sympathetic",
    "Compliant, Submissive, Dutiful, Respectful, Deferential, Obedient, Conforming, Passive, Docile, Yielding", 
    "Perceptive, Insightful, Discerning, Vigilant, Mindful, Attentive, Keen, Watchful, Noticing, Acutely aware",
    "Receptive, Tolerant, Broad-minded, Liberal, Unprejudiced, Objective, Unbiased, Impartial, Nonjudgmental, Flexible",
    "Positive, Hopeful, Confident, Upbeat, Cheerful, Encouraging, Bright, Promising, Favorable, Auspicious",
    "Organized, Methodical, Systematic, Structrued, Neat, Tidy, Regimented, Composed, Disciplined, Arranged",
    "Extroverted, Sociable, Friendly, Interactive, Lively, Expressive, Gregarious, Talkative, Vivacious, Animated",
    "Nurturing, Caring, Loving, Protective, Guiding, Supportive, Selfless, Devoted, Sacrificing, Responsible",
    "Supportive, Understanding, Collaborative, Companionable, Cooperative, Communicative, Sharing, United, Allied, Harmonious",
    "Tolerant, Understanding, Unflappable, Composed, Resilient, Stoic, Long-suffering, Imperturbable, Uncomplaining, Serene",
    "Calm, Tranquil, Harmonious, Serene, Placid, Quiet, Stable, Undisturbed, Halcyon, Nonviolent",
    "Thoughtful, Contemplative, Reflective, Meditative, Wistful, Dreamy, Introspective, Retrospective, Brooding, Deliberative",
    "Insightful, Observant, Intuitive, Discerning, Shrewd, Astute, Sagacious, Judicious, Discriminating, Keen",
    "Precise, Meticulous, Rigorous, Demanding, Uncompromising, Strict, Conscientious, Critical, Fussy, Particular",
    "Steadfast, Persistent, Tenacious, Resolute, Determined, Diligent, Unwavering, Unfaltering, Indefatigable, Tireless", 
    "Convincing, Compelling, Influential, Cogent, Eloquent, Articulate, Forceful, Authoritative, Contagious, Impressive",
    "Contemplative, Thoughtful, Reasoned, Rational, Analytical, Metaphysical, Meditative, Reflective, Profound, Abstract",
    "Frank, Candid, Direct, Forthright, Blunt, Unambiguous, Explicit, Clear-cut, Matter-of-fact, Straightforward",
    "Fun, Funny, Humorous, Witty, Cheeky, Joking, Whimsical, Mischievous, Lighthearted, Comedic",  
    "Confident, Composed, Collected, Self-possessed, Assured, Equilibrium, Balanced, Tranquil, Unruffled, Serene",
    "Courteous, Well-mannered, Civil, Respectful, Cultured, Refined, Diplomatic, Tactful, Gracious, Cordial",
    "Upbeat, Optimistic, Hopeful, Encouraging, Constructive, Affirmative, Confident, Promising, Bright, Auspicious",
    "Practical, Sensible, Realistic, Down-to-earth, Logical, Reasonable, Rational, Level-headed, Matter-of-fact, Expedient", 
    "Exact, Accurate, Meticulous, Rigorous, Thorough, Perfect, Methodical, Careful, Word-for-word, Letter-perfect",
    "Ethical, Righteous, Upright, Honorable, High-minded, Idealistic, Noble, Discreet, Conscientious, Moralistic",
    "Initiative, Enterprising, Driven, Energetic, Pioneering, Determined, Dynamic, Motivated, Progressive, Ambitious",
    "Skilled, Expert, Efficient, Businesslike, Competent, Trained, Qualified, Methodical, Systematic, Conscientious",
    "Safeguarding, Defending, Shielding, Careful, Cautious, Prudent, Concerned, Mindful, Attentive, Sheltering",
    "Wise, Discreet, Cautious, Judicious, Sensible, Careful, Thoughtful, Deliberate, Practical, Shrewd",
    "Prompt, On-time, Precise, Regular, Organized, Timely, Scheduled, Regimented, Systematic, Dependable",
    "Innocent, Virginal, Wholesome, Virtuous, Moral, Decent, Upright, Modest, Untainted, Uncorrupted",
    "Reserved, Shy, Silent, Demure, Tranquil, Still, Introverted, Peaceful, Calm, Mild-mannered",
    "Eccentric, Odd, Peculiar, Idiosyncratic, Unconventional, Offbeat, Strange, Weird, Bizarre, Singular",
    "Logical, Reasonable, Sensible, Practical, Realistic, Sane, Level-headed, Coherent, Analytical, Clear-thinking",
    "Practical, Pragmatic, Down-to-earth, Valid, Authentic, Genuine, Tangible, Commonsensical, Level-headed, Well-grounded",
    "Defiant, Disobedient, Unruly, Recalcitrant, Uncontrollable, Noncompliant, Disruptive, Wayward, Resistant, Obstinate", 
    "Contemplative, Thoughtful, Meditative, Mindful, Philosophical, Pondering, Ruminative, Introspective, Retrospective, Wistful",
    "Dependable, Trustworthy, Responsible, Consistent, Steady, Reputable, Conscientious, Stable, Tried and true, Solid",
    "Tough, Hardy, Robust, Durable, Tenacious, Indestructible, Unbreakable, Sturdy, Unshakable, Determined",  
    "Inventive, Imaginative, Creative, Enterprising, Clever, Adaptable, Ingenious, Handy, Capable, Practical",
    "Polite, Courteous, Civil, Deferential, Reverent, Honorable, Considerate, Thoughtful, Regardful, Esteeming",
    "Reliable, Dependable, Trustworthy, Conscientious, Dutiful, Accountable, Answerable, Obligated, Answerable, Capable",
    "Reserved, Controlled, Repressed, Measured, Moderate, Temperate, Disciplined, Contained, Muted, Subdued",
    "Respectful, Solemn, Sacred, Spiritual, Devout, Pious, Religious, Holy, Hallowed, Venerating",
    "Passionate, Affectionate, Ardent, Fervent, Loving, Tender, Amorous, Sentimental, Intimate, Emotional", 
    "Ironic, Cynical, Mocking, Scornful, Contemptuous, Derisive, Satirical, Sneering, Caustic, Snarky",
    "Academic, Learned, Bookish, Studious, Erudite, Intellectual, Knowledgeable, Informed, Well-read, Literary",
    "Analytical, Methodical, Experimental, Observant, Investigative, Logical, Systematic, Rational, Technical, Precise",
    "Confident, Poised, Composed, Firm, Unwavering, Decisive, Assertive, Sure, Positive, Bold",
    "Restrained, Principled, Regulated, Strict, Rigorous, Controlled, Resolute, Focused, Determined, Teetotaler",
    "Altruistic, Unselfish, Charitable, Benevolent, Magnanimous, Generous, Philanthropic, Sacrificing, Humanitarian, Noble",
    "Empathetic, Compassionate, Caring, Intuitive, Understanding, Sensible, Perceptive, Sympathetic, Warm, Tenderhearted", 
    "Nostalgic, Wistful, Yearning, Sad, Attached, Emotional, Romantic, Affectionate, Tender, Passionate",
    "Solemn, Sober, Sincere, Grave, Earnest, Severe, Grim, Humorless, Resolute, Uncompromising",
    "Astute, Savvy, Clever, Cunning, Crafty, Calculating, Judicious, Insightful, Prudent, Artful",
    "Foolish, Ridiculous, Absurd, Preposterous, Zany, Outlandish, Wacky, Goofy, Lighthearted, Nonsensical",
    "Genuine, Earnest, Heartfelt, Candid, Direct, Honest, Truthful, Authentic, Open, Transparent",
    "Expert, Masterful, Proficient, Accomplished, Talented, Trained, Polished, Seasoned, Savvy, Adroit",
    "Brilliant, Intelligent, Clever, Quick-witted, Genius, Gifted, Bright, Astute, Savvy, Sharp",
    "Friendly, Outgoing, Gregarious, Congenial, Affable, Garrulous, Conversational, Talkative, Companionable, Hospitable",
    "Cultured, Refined, Civilized, Cosmopolitan, Urbanized, Polished, Suave, Debonair, Worldly, Discerning",
    "Devout, Pious, Religious, Sacred, Divine, Reverent, Rapturous, Mystical, Transcendent, Enlightened",
    "Impulsive, Unplanned, Unpremeditated, Unscripted, Impromptu, Natural, Instinctive, Intuitive, Impetuous, Unrehearsed",
    "Stable, Secure, Constant, Reliable, Solid, Firm, Unwavering, Unflinching, Unflappable, Unvarying",
    "Impassive, Unemotional, Dispassionate, Unperturbed, Composed, Imperturbable, Resigned, Equable, Steely, Philosophical",
    "Stubborn, Headstrong, Resolute, Determined, Obstinate, Unyielding, Tenacious, Inflexible, Opposite, Uncompromising",
    "Scholarly, Academic, Bookish, Intellectual, Learned, Diligent, Dedicated, Attentive, Curious, Inquisitive",
    "Foolish, Unintelligent, Ignorant, Dim-witted, Brainless, Mindless, Oblivious, Slow, Dull, Dense",
    "Charming, Debonair, Sophisticated, Urbane, Stylish, Slick, Smooth, Refined, Worldly, Cultured",
    "Docile, Compliant, Obedient, Passive, Resigned, Meek, Subservient, Deferential, Timid, Unresisting",
    "Helpful, Encouraging, Nurturing, Assisting, Backing, Advocating, Promoting, Bolstering, Reinforcing, Comforting",  
    "Kind, Caring, Pleasant, Agreeable, Good-natured, Friendly, Helpful, Thoughtful, Obliging, Generous",
    "Compassionate, Empathetic, Understanding, Caring, Considerate, Kind, Thoughtful, Relating, Warmhearted, Commiserating",
    "Methodical, Ordered, Organized, Structured, Programmed, Logical, Planned, Procedural, Sequential, Regimented",
    "Specialized, Mechanical, Practical, Methodical, Systematic, Analytical, Precise, Skilled, Technological, Engineered",
    "Kind, Compassionate, Caring, Loving, Sensitive, Warm, Sympathetic, Understanding, Gentle, Softhearted",
    "Comprehensive, Exhaustive, Complete, Meticulous, Diligent, Precise, Rigorous, In-depth, Detailed, Systematic", 
    "Neat, Orderly, Organized, Uncluttered, Arranged, Composed, Systematic, Methodical, Unmessy, Well-kept",
    "Accepting, Patient, Broad-minded, Open-minded, Indulgent, Liberal, Permissive, Forgiving, Lenient, Allowing",
    "Strong, Resilient, Robust, Hardy, Rugged, Durable, Stalwart, Sturdy, Hardened, Hard-as-nails",
    "Conventional, Customary, Established, Long-standing, Classical, Conservative, Orthodox, Time-honored, Old-fashioned, Staid",
    "Crafty, Cunning, Mischievous, Sly, Devious, Artful, Wily, Elusive, Scheming, Clever",
    "Faithful, Unsuspecting, Reliant, Believing, Accepting, Confident, Optimistic, Hopeful, Credulous, Dependable",
    "Humble, Modest, Down-to-earth, Unpretentious, Self-effacing, Unobtrusive, Plain, Ordinary, Simple, Unaffected",
    "Compassionate, Sympathetic, Empathetic, Tolerant, Patient, Perceptive, Insightful, Accommodating, Forgiving, Accepting",
    "Composed, Calm, Collected, Unruffled, Imperturbable, Unshakable, Steady, Even-tempered, Cool-headed, Impassive",
    "Distinct, Rare, Uncommon, Special, Singular, One-of-a-kind, Different, Standout, Extraordinary, Unparalleled",
    "Erratic, Irregular, Inconsistent, Unstable, Variable, Capricious, Mercurial, Volatile, Unforeseeable, Undependable",
    "Simple, Plain, Modest, Unassuming, Unaffected, Self-effacing, Down-to-earth, Unobtrusive, Natural, Unprepossessing", 
    "Positive, Optimistic, Hopeful, Encouraging, Cheerful, Promising, Bright, Auspicious, Confident, Hyped",
    "Sophisticated, Refined, Polished, Suave, Cosmopolitan, Worldly, Cultured, Civilized, Gentrified, Stylish",
    "Adaptable, Flexible, Multitalented, Resourceful, All-purpose, Multifaceted, Multiskilled, Well-rounded, Dynamic, Agile",
    "Watchful, On-guard, Alert, Observant, Wary, Mindful, Attentive, Cautious, Hedging, Argus-eyed",
    "Lively, Animated, Spirited, Bubbly, Energetic, Vibrant, Zestful, Dynamic, Playful, Peppy",
    "Caring, Kind, Compassionate, Considerate, Benevolent, Sympathetic, Thoughtful, Altruistic, Charitable, Loving",
    "Fanciful, Playful, Quirky, Witty, Capricious, Frivolous, Unconventional, Eccentric, Zany, Lighthearted",
    "Sagacious, Prudent, Discerning, Judicious, Sensible, Shrewd, Astute, Savvy, Perceptive, Insightful",
    "Clever, Humorous, Amusing, Entertaining, Comedic, Smart, Funny, Jocular, Sparkling, Playful", 
    "Young, Vibrant, Fresh, Lively, Sprightly, Vivacious, Energetic, Spirited, Playful, Lighthearted",
    "Wacky, Goofy, Slapstick, Kooky, Crazy, Eccentric, Quirky, Wild, Madcap, Off-the-wall",
    "Passionate, Fervent, Devoted, Ardent, Enthusiastic, Intense, Gung-ho, Fanatical, Overt, Extreme",
    //[NSFW]
    "*Unyielding, Manipulative, Intimidating, Aggressive, Controlling, Deceptive, Vindictive, Cruel, Unpredictable, Insensitive",
    "*Drug addict, Fixated, Obsessed, Uncontrolled, Desperate, Withdrawn, Dependent, Fixated, Hooked, Enslaved",
    "*Disoriented, Impulsive, Unpredictable, Irresponsible, Neglectful, Unstable, Reckless, Regretful, Disoriented, Isolated",
    "*Disinterested in sex, Non-sexual, Abstinent, Celibate, Platonic, Passionless, Frigid, Cold, Disconnected, Detached",
    "*Dishonest, Unfaithful, Sly, Unreliable, Conniving, Cunning, Deceptive, Treacherous, Two-faced, Double-dealing",
    "*Teasing, Coy, Kittenish, Frisky, Sexy, Coquettish, Captivating, Flirtatious, Playful, Bewitching",
    "*Uninhibited, Impulsive, Sensual, Indulgent, Adventurous, Energetic, Passionate, Daring, Lustful, Wild",
    "*Hopeless, Melancholic, Sad, Apathetic, Isolated, Tired, Pessimistic, Unmotivated, Despairing, Gloomy",
    "*Yearning, Longing, Yearning, Impatient, Ambitious, Restless, Enthusiastic, Determined, Passionate, Eager",
    "*Confident, Glamorous, Charismatic, Alluring, Extravagant, Bold, Sensual, Dominant, Passionate, Unapologetic",
    "*Assertive, In control, Confident, Strong-willed, Firm, Decisive, Courageous, Bold, Disciplined, Demanding",
    "*Commanding, Demanding, Assertive, Strict, Controlling, Power-hungry, Rigid, Domineering, Autocratic, Authoritarian",
    "*Promiscuous, Loose, Trashy, Unprincipled, Amenable, Carefree, Accessible, Reckless, Irresponsible, Negligent",
    "*Likes to be seen, Adventurous, Outgoing, Confident, Uninhibited, Bold, Playful, Spontaneous, Daring, Open-minded",
    "*Passionate, Devoted, Excitable, Single-minded, Curious, Adventurous, Expressive, Open-minded, Enthusiastic, Obsessive",
    "*Mischievous, Playful, Light-hearted, Charismatic, Witty, Confident, Charming, Entertaining, Energetic, Expressive",
    "*Close, Personal, Private, Familiar, Trusted, Cherished, Treasured, Beloved, Confidential, Secret",
    "*Cold-hearted, Heartless, Impulsive, Remorseless, Deceptive, Dangerous, Ruthless, Unpredictable, Violent, Merciless",
    "*Devoted, Affectionate, Ardent, Passionate, Fervent, Enamored, Smitten, Besotted, Devoted, Attached",
    "*Covetous, Greedy, Avaricious, Desirous, Desiring, Ravenous, Voracious, Insatiable, Famished, Starving",
    "*Self-punishing, Self-denying, Enduring, Submissive, Enduring, Stoic, Long-suffering, Meek, Self-sacrificing, Mortifying",
    "*Uninhibited, Natural, Open, Comfortable, Free-spirited, Non-judgmental, Relaxed, Adventurous, Body-positive, Confident",
    "*Female, Feminine, Graceful, Delicate, Refined, Dainty, Picturesque, Idyllic, Pastoral, Arcadian",
    "*Obsessive, Unceasing, Excessive, Extreme, Immoderate, Unrestrained, Uncontrolled, Unmanageable, Unquenchable, Unsatisfiable",
    "*Enduring, Patient, Submissive, Resilient, Brave, Tolerant, Eager, Humble, Resistant, Self-harm",
    "*Loving, Open-hearted, Honest, Communicative, Understanding, Flexible, Generous, Respectful, Adaptable, Empathetic",
    "*Dominant, Instinctive, Animalistic, Passionate, Rough, Impulsive, Powerful, Wild, Assertive, Untamed",
    "*Exploited, Abused, Victimized, Marginalized, Oppressed, Subservient, Disenfranchised, Ostracized, Stigmatized, Maltreated",
    "*Daring, Disruptive, Adventurous, Controversial, Subversive, Challenging, Defiant, Rebellious, Confrontational, Disobedient",
    "*Duplicitous, Impulsive, Callous, Unemotional, Deceptive, Insincere, Irresponsible, Reckless, Narcissistic, Charming",
    "*Bigoted, Prejudiced, Biased, Discriminatory, Hateful, Xenophobic, Intolerant, Anti-Semitic, Supremacist, Chauvinistic",
    "*Cruel, Brutal, Inhumane, Merciless, Ruthless, Savage, Vicious, Malicious, Heartless, Unsympathetic",
    "*Licentious, Libidinous, Seductive, Lascivious, Lewd, Debauched, Tainted, Impure, Corrupted, Depraved",
    "*Tempting, Enticing, Tantalizing, Bewitching, Enchanting, Captivating, Mesmerizing, Hypnotic, Beguiling, Alluring",
    "*Tactile, Passionate, Appreciative, In the moment, Sensitive, Intuitive, Romantic, Attuned, Indulgent, Patient",
    "*Addicted, Compulsive, Obsessed, Predatory, Insatiable, Ravenous, Voracious, Craving, Lustful, Desperate",
    "*Passionate, Lustful, Sensual, Carnal, Amorous, Romantic, Affectionate, Loving, Intimate, Ardent",
    "*Subjugated, Subordinate, Subservient, Obedient, Servile, Beholden, Indentured, Subject, Bondsman, Thrall",
    "*Wild, Uninhibited, Sex partner, Open, Audacious, Flirtatious, Easygoing, Slutty, Temptress, Sexual Obsessive", 
    "*Docile, Passive, Compliant, Obedient, Yielding, Deferential, Respectful, Servile, Obsequious, Self-effacing",
    "*Open-minded, Adventurous, Sociable, Flexible, Communicative, Respectful, Fun-loving, Friendly, Non-jealous, Confident",
    "*Seductress, Enchantress, Siren, Vixen, Bewitcher, Charmer, Belle, Circe, Delilah, Lorelei",
    "*Iconoclastic, Heretical, Contrary, Disobedient, Subversive, Unorthodox, Defiant, Radical, Nonconformist, Unconventional",
    "*Disloyal, Betraying, Treacherous, Deceitful, Adulterous, False, Untrue, Backstabbing, Double-crossing, Perfidious",
    "*Vulnerable, Insecure, Fearful, Defensive, Quiet, Submissive, Anxious, Pessimistic, Sensitive, Resigned",
    "*Aggressive, Impulsive, Explosive, Volatile, Unpredictable, Intimidating, Ruthless, Brutal, Fierce, Destructive",
    "*Chaste, Virtuous, Innocent, Pure, Maidenly, Untouched, Wholesome, Immaculate, Fresh, Unspoiled",
    "*Peeping Tom, Snoop, Spy, Sneak, Peeper, Lurker, Eavesdropper, Intruder, Interloper, Trespasser",
    "*Coarse, Crass, Rude, Offensive, Indelicate, Crude, Foul, Profane, Smutty, Obscene",
    "*Harlot, Call girl, Tempting, Hooker, Streetwalker, Hustler, Seductive, Working girl, Escort, Courtesan"
];

const description = [
    "Possesses a deep love for learning and a strong intellectual curiosity, often immersed in studies and scholarly pursuits.",
    "Easily adjusts to new situations and environments, showing flexibility and resilience in the face of change.",
    "Thrives on excitement and the thrill of exploring the unknown, always seeking new experiences.",
    "Expresses love and warmth openly, valuing close relationships and emotional connections.",
    "Approaches problems and situations with a logical, detail-oriented mindset, often breaking down complex issues into manageable parts.",
    "Tends to worry and feel uneasy, often overthinking situations and fearing potential outcomes.",
    "Has a natural talent for creativity and expression, often engaging in artistic pursuits like painting, writing, or music.",
    "Communicates clearly and effectively, able to convey thoughts and ideas with precision and eloquence.",
    "Values physical fitness and sports, often engaging in regular exercise and competitive activities.",
    "Stays true to oneself, valuing honesty and integrity, and presenting oneself genuinely.",
    "Maintains composure and serenity even in stressful situations, often acting as a soothing presence for others.",
    "Possesses the skills and competence to handle tasks and challenges effectively, often achieving goals efficiently.",
    "Approaches situations with care and prudence, often considering potential risks and consequences before acting.",
    "Exudes a magnetic and appealing personality, easily attracting and captivating others.",
    "Radiates happiness and positivity, often lifting the spirits of those around them.",
    "Displays a playful and youthful demeanor, sometimes lacking maturity or seriousness.",
    "Quick-witted and resourceful, often finding creative solutions to problems.",
    "Shows deep empathy and concern for others, often going out of their way to help those in need.",
    "Possesses a multifaceted and intricate personality, often difficult to fully understand or categorize.",
    "Self-assured and poised, often taking initiative and leading with conviction.",
    "Engages in deep thought and reflection, often pondering life's big questions and seeking understanding.",
    "Works well with others, valuing teamwork and collaboration to achieve common goals.",
    "Faces challenges and fears head-on, often displaying bravery and determination in difficult situations.",
    "Exhibits unconventional and unpredictable behavior, often embracing spontaneity and eccentricity.",
    "Generates innovative ideas and artistic expressions, often thinking outside the box.",
    "Eager to learn and explore, always seeking to discover new information and experiences.",
    "Shrewd and calculating, often using clever tactics to achieve desired outcomes.",
    "Makes decisions quickly and confidently, often taking firm action in uncertain situations.",
    "Shows unwavering loyalty and dedication, often putting the needs and desires of loved ones first.",
    "Handles sensitive situations with tact and grace, often mediating conflicts and fostering harmony.",
    "Expresses emotions intensely and vividly, often making situations more theatrical or exaggerated.",
    "Fulfills responsibilities and obligations diligently, often putting duty and honor above personal desires.",
    "Energetic and full of life, often adapting quickly to changing circumstances and inspiring others with their vigor.",
    "Sincere and serious in intentions and efforts, often approaching tasks with genuine dedication.",
    "Displays quirky and unconventional behavior, often standing out with unique traits and habits.",
    "Well-informed and knowledgeable, often possessing a strong academic background and intellectual prowess.",
    "Completes tasks quickly and effectively, often optimizing processes to save time and resources.",
    "Expresses oneself with fluency and grace, often captivating listeners with persuasive speech.",
    "Understands and shares the feelings of others, often providing emotional support and comfort.",
    "Full of vitality and enthusiasm, often approaching life with a lively and spirited attitude.",
    "Captures and holds attention easily, often creating stimulating and interactive conversations.",
    "Mysterious and intriguing, often leaving others curious and fascinated by their persona.",
    "Displays eager interest and excitement, often inspiring others with their passionate outlook.",
    "Adheres to moral principles and values, often prioritizing integrity and honesty in actions and decisions.",
    "Enjoys lavish and opulent lifestyles, often indulging in luxury and excess.",
    "Treats others with impartiality and justice, often striving for equality and fairness in interactions.",
    "Remains loyal and steadfast, often showing unwavering commitment to relationships and causes.",
    "Prioritizes family values and relationships, often placing family at the center of their life.",
    "Exhibits qualities traditionally associated with femininity, often emphasizing grace, nurturing, and sensitivity.",
    "Displays intense determination and strength, often fiercely protecting and advocating for their beliefs and loved ones.",
    "Lacks good judgment or sense, often making unwise decisions or acting imprudently.",
    "Shows a willingness to forgive and move past transgressions, often valuing reconciliation and healing.",
    "Approachable and kind-hearted, often making others feel welcome and comfortable in their presence.",
    "Brings joy and entertainment to others, often creating a lively and enjoyable atmosphere.",
    "Passionately interested in niche or technical subjects, often displaying deep enthusiasm for hobbies and interests.",
    "Willingly shares time, resources, and kindness with others, often going out of their way to help.",
    "Kind and mild-mannered, often handling situations and people with care and softness.",
    "Selflessly provides for others, often putting the needs and well-being of others above their own.",
    "Shows courtesy and politeness, often displaying elegance and charm in interactions.",
    "Enjoys socializing and being around people, often thriving in social settings and making new friends easily.",
    "Down-to-earth and practical, often staying realistic and sensible in their approach to life.",
    "Protective of their emotions and personal information, often keeping a safe distance from others.",
    "Eager to assist and support, often providing aid and solutions to those in need.",
    "Maintains a positive outlook on the future, often expecting good outcomes and believing in the best possibilities.",
    "Modest and unassuming, often downplaying their achievements and valuing the contributions of others.",
    "Excited and enthusiastic, often expressing eagerness and energy about events or activities.",
    "Extremely energetic and active, often displaying restless and exuberant behavior.",
    "Holds high ideals and principles, often striving for perfection and believing in noble causes.",
    "Rich in creativity and fantasy, often coming up with inventive ideas and stories.",
    "Acts on whims and sudden desires, often without considering the consequences.",
    "Self-reliant and autonomous, often valuing freedom and self-sufficiency.",
    "Hard-working and diligent, often putting in consistent effort to achieve goals and complete tasks.",
    "Possesses deep understanding and perception, often providing profound observations and ideas.",
    "Highly knowledgeable and quick to understand, often excelling in intellectual pursuits.",
    "Displays strong and powerful emotions or actions, often creating a passionate and compelling presence.",
    "Relies on gut feelings and instincts, often making decisions based on an inner sense of understanding.",
    "Creates innovative solutions and ideas, often approaching problems with original and creative thinking.",
    "Radiates happiness and contentment, often spreading cheer and positivity to others.",
    "Sharply observant and enthusiastic, often showing eagerness and quickness in understanding or reacting.",
    "Displays warmth and generosity, often acting with compassion and empathy towards others.",
    "Well-versed and informed in various subjects, often sharing information and insights with others.",
    "Relaxed and easy-going, often taking a casual and stress-free approach to life.",
    "Maintains calm and rational thinking, often making balanced and sound decisions.",
    "Frequently tells falsehoods or deceives others, often manipulating situations through dishonesty.",
    "Full of energy and spirit, often bringing vibrancy and excitement to interactions.",
    "Uses clear and rational thinking, often approaching problems and situations with reason and analysis.",
    "Expresses deep affection and care, often prioritizing close and meaningful relationships.",
    "Devoted and faithful, often standing by friends, family, and commitments through thick and thin.",
    "Exhibits qualities traditionally associated with masculinity, often emphasizing strength, assertiveness, and independence.",
    "Displays wisdom and emotional stability, often acting with responsibility and consideration.",
    "Approaches tasks and problems in a systematic and organized manner, often planning and executing with precision.",
    "Pays great attention to detail, often ensuring accuracy and thoroughness in tasks.",
    "Attentive and aware of the present moment, often practicing mindfulness and consideration in actions.",
    "Humble and unpretentious, often downplaying achievements and valuing simplicity.",
    "Possesses a talent for music, often engaging in musical activities or appreciating musical expressions.",
    "Organized and tidy, often maintaining order and cleanliness in surroundings.",
    "Passionately interested in specific subjects or hobbies, often displaying deep enthusiasm and expertise.",
    "Possesses high moral principles and ideals, often acting with honor and integrity.",
    "Provides care and support, often fostering growth and well-being in others.",
    "Follows rules and instructions willingly, often showing compliance and respect for authority.",
    "Keenly attentive to details and surroundings, often noticing things that others might miss.",
    "Willing to consider new ideas and perspectives, often embracing diversity and change.",
    "Maintains a hopeful and positive outlook on life, often expecting the best outcomes.",
    "Values organization and structure, often keeping things neat and systematic.",
    "Sociable and extroverted, often enjoying meeting new people and engaging in social activities.",
    "Displays nurturing and protective qualities, often guiding and caring for others like a parent.",
    "Values close and committed relationships, often prioritizing the needs and well-being of their partner.",
    "Shows tolerance and understanding, often waiting calmly and dealing with delays or challenges without frustration.",
    "Values harmony and tranquility, often avoiding conflict and promoting calmness.",
    "Deep in thought and reflection, often contemplating life and its complexities.",
    "Highly observant and insightful, often understanding things quickly and accurately.",
    "Strives for flawlessness and excellence, often setting high standards for oneself and others.",
    "Displays determination and persistence, often overcoming obstacles through consistent effort.",
    "Skilled in convincing others, often using effective communication and reasoning to influence decisions.",
    "Engages in deep thinking about fundamental questions and ideas, often pondering the meaning of life and existence.",
    "Communicates directly and honestly, often expressing thoughts and opinions without embellishment.",
    "Enjoys fun and games, often bringing a sense of joy and light-heartedness to interactions.",
    "Exhibits composure and grace, often maintaining balance and elegance in various situations.",
    "Shows good manners and courtesy, often being considerate and respectful in interactions.",
    "Maintains an optimistic and hopeful outlook, often focusing on the good in situations and people.",
    "Approaches situations practically and realistically, often finding effective and workable solutions.",
    "Pays close attention to accuracy and detail, often ensuring exactness in tasks and communication.",
    "Adheres to strong moral values and ethics, often standing by beliefs and acting with integrity.",
    "Takes initiative and anticipates needs, often acting in advance to address potential issues.",
    "Conducts oneself with competence and respect, often maintaining high standards in work and interactions.",
    "Guards and defends loved ones, often prioritizing their safety and well-being.",
    "Exercises careful judgment and foresight, often making wise and cautious decisions.",
    "Values timeliness and reliability, often arriving and completing tasks on schedule.",
    "Innocent and untainted, often displaying simplicity and moral integrity.",
    "Soft-spoken and reserved, often preferring to listen rather than speak.",
    "Displays unique and unconventional traits, often standing out with distinctive personality features.",
    "Thinks logically and sensibly, often basing decisions on reason and evidence.",
    "Sees things as they are, often dealing with situations practically and without idealism.",
    "Resists authority and convention, often challenging rules and societal norms.",
    "Engages in thoughtful consideration, often examining experiences and ideas deeply.",
    "Dependable and trustworthy, often fulfilling commitments and responsibilities consistently.",
    "Recovers quickly from setbacks and adversity, often displaying strength and perseverance.",
    "Finds innovative solutions and makes the best use of available resources, often adapting to challenges effectively.",
    "Shows consideration and regard for others, often valuing their opinions and treating them with kindness.",
    "Takes ownership of actions and duties, often fulfilling obligations reliably and conscientiously.",
    "Exercises self-control and moderation, often avoiding excessive behavior and acting with restraint.",
    "Shows deep respect and admiration, often valuing tradition and honoring esteemed figures or principles.",
    "Values love and passion, often expressing deep affection and creating meaningful emotional connections.",
    "Uses sharp and ironic humor, often expressing criticism or mockery in a witty manner.",
    "Engages in academic and intellectual pursuits, often valuing education and the pursuit of knowledge.",
    "Approaches problems and questions with a methodical and evidence-based mindset, often valuing empirical research.",
    "Possesses a clear understanding of oneself, often recognizing personal strengths and weaknesses.",
    "Holds a strong belief in one's abilities, often approaching tasks with assurance and poise.",
    "Prioritizes the needs and well-being of others, often acting with altruism and generosity.",
    "Easily affected by emotions and external stimuli, often displaying empathy and emotional awareness.",
    "Holds deep emotional attachments to memories and traditions, often valuing nostalgia and personal connections.",
    "Approaches life and tasks with gravity and earnestness, often prioritizing responsibility and focus.",
    "Displays astuteness and sharp judgment, often making smart and calculated decisions.",
    "Engages in playful and light-hearted behavior, often bringing humor and fun to interactions.",
    "Genuinely expresses thoughts and feelings, often valuing honesty and authenticity.",
    "Possesses proficiency and expertise in various tasks, often excelling in specific skills or talents.",
    "Quick to understand and learn, often demonstrating intelligence and mental acuity.",
    "Enjoys being around people and engaging in social activities, often forming connections easily.",
    "Exhibits refined taste and manners, often appreciating culture, elegance, and intellectual pursuits.",
    "Values inner peace and connection to a higher purpose, often engaging in practices that nurture the soul.",
    "Acts on impulse and without planning, often embracing the excitement of the moment.",
    "Consistent and reliable, often maintaining stability and dependability in actions and behavior.",
    "Remains calm and unaffected by emotions, often displaying resilience and endurance in difficult situations.",
    "Displays physical or emotional strength, often overcoming challenges with power and determination.",
    "Diligent and dedicated to learning, often spending time and effort on academic or intellectual pursuits.",
    "Lacks intelligence or common sense, often making poor decisions or displaying ignorance.",
    "Charming and confident, often displaying smooth and sophisticated manners.",
    "Agreeable and accommodating, often putting others' preferences and desires first.",
    "Provides encouragement and assistance, often helping others achieve their goals and overcome challenges.",
    "Kind and gentle, often displaying affection and consideration in interactions.",
    "Shows understanding and compassion for others' feelings and experiences, often offering comfort and support.",
    "Approaches tasks and problems methodically, often valuing organization and structure.",
    "Skilled in practical and mechanical tasks, often possessing expertise in specific technical fields.",
    "Shows deep compassion and sensitivity, often caring for others with kindness and empathy.",
    "Pays careful attention to detail, often ensuring completeness and accuracy in tasks.",
    "Keeps things neat and organized, often valuing cleanliness and order.",
    "Accepts and respects different views and behaviors, often embracing diversity and inclusivity.",
    "Resilient and strong-willed, often enduring hardships and facing challenges with determination.",
    "Values customs and conventions, often adhering to established practices and beliefs.",
    "Enjoys playing pranks and creating mischief, often displaying a playful and cunning nature.",
    "Believes in the honesty and reliability of others, often showing faith and confidence in people.",
    "Modest and unpretentious, often downplaying achievements and avoiding the spotlight.",
    "Comprehends and empathizes with others' situations and feelings, often providing support and compassion.",
    "Remains calm and composed under pressure, often handling stressful situations with ease.",
    "Distinctive and individual, often standing out with one-of-a-kind traits and characteristics.",
    "Difficult to anticipate, often displaying unexpected and surprising behavior.",
    "Simple and humble, often avoiding ostentation and valuing authenticity.",
    "Cheerful and positive, often maintaining a hopeful and enthusiastic outlook.",
    "Sophisticated and cultured, often displaying polished manners and refined tastes.",
    "Adaptable and multi-talented, often excelling in various fields and tasks.",
    "Watchful and alert, often paying close attention to potential dangers or changes.",
    "Full of life and energy, often bringing enthusiasm and spirit to interactions.",
    "Kind and affectionate, often displaying warmth and compassion towards others.",
    "Playfully imaginative, often engaging in fanciful and light-hearted activities.",
    "Possesses deep knowledge and good judgment, often offering valuable advice and insight.",
    "Clever and humorous, often using sharp and quick-thinking humor in interactions.",
    "Displays a sense of freshness and vigor, often maintaining a lively and energetic demeanor.",
    "Unconventional and eccentric, often bringing a sense of humor and whimsy to interactions.",
    "Passionately devoted and enthusiastic, often showing fervent dedication to a cause or activity.",
    "Exhibits harmful and violent behavior towards others, often causing physical or emotional pain.",
    //[NSFW]
    "*Exhibits harmful and violent behavior towards others, often causing physical or emotional pain.",
    "*Engages in compulsive and dependent behavior, often forming unhealthy attachments.",
    "*Habitually consumes alcohol to excess, often struggling with dependency.",
    "*Lacks sexual attraction or desire, often valuing emotional connections over physical ones.",
    "*Engages in dishonest or deceitful behavior, often breaking trust in relationships.",
    "*Flirtatious and playful in a teasing manner, often attracting attention and admiration.",
    "*Indulges in excessive and immoral behaviors, often lacking restraint or moderation.",
    "*Experiences persistent feelings of sadness and hopelessness, often struggling with emotional well-being.",
    "*Strongly wants or craves something, often driven by intense longing.",
    "*Attracts desire and admiration, often possessing qualities that are appealing to others.",
    "*Exudes confidence and a sense of command, often taking the lead in interactions.",
    "*Exercises control and power in a sexual context, often dominating partners with authority.",
    "*Relaxed and carefree, often taking a laid-back approach to life and interactions.",
    "*Enjoys displaying oneself publicly, often seeking attention and admiration.",
    "*Possesses an intense and specific sexual attraction to particular objects or activities.",
    "*Engages in playful and suggestive behavior, often seeking romantic or sexual attention.",
    "*Seeks close and personal connections, often valuing deep emotional and physical bonds.",
    "*Causes the death of others, often displaying violent and lethal behavior.",
    "*Passionate and deeply emotional, valuing strong emotional bonds and intimate connections.",
    "*Driven by strong sexual desire, often seeking physical pleasure and gratification.",
    "*Derives pleasure from experiencing pain or humiliation, often seeking such experiences deliberately.",
    "*Prefers to be without clothing, often valuing freedom and naturalness.",
    "*Displays a youthful and alluring charm, often exuding an ethereal and playful allure.",
    "*Driven by a compulsive desire for sexual activity, often seeking frequent and varied encounters.",
    "*Actively pursues experiences that cause physical or emotional pain.",
    "*Engages in multiple romantic relationships simultaneously, often valuing openness and communication.",
    "*Exploits others for personal gain, often displaying manipulative and harmful behavior.",
    "*Engages in sexual activities in exchange for money or other benefits.",
    "*Intentionally incites reactions, often displaying bold and controversial behavior.",
    "*Exhibits antisocial and manipulative behavior, often lacking empathy and remorse.",
    "*Displays prejudice and discrimination based on race, often believing in the superiority of one's own race.",
    "*Derives pleasure from causing pain and suffering to others, often displaying cruel and ruthless behavior.",
    "*Possesses an excessive and often uncontrolled sexual desire, often engaging in promiscuous behavior.",
    "*Captivates with charm and allure, often enticing others with a magnetic and provocative presence.",
    "*Values and seeks out physical pleasure and sensory experiences, often indulging in tactile and hedonistic activities.",
    "*Compulsively seeks out sexual experiences, often struggling with an addiction to sex.",
    "*Possesses a strong interest and drive for sexual activity, often valuing physical intimacy.",
    "*Submissive and obedient, often displaying a willingness to serve and please others.",
    "*Engages in promiscuous and casual sexual activities, often without emotional attachment.",
    "*Agreeable and accommodating, often putting others' preferences and desires first.",
    "*Participates in consensual non-monogamous sexual activities, often engaging with multiple partners.",
    "*Captivates with an alluring and playful charm, always leaving an air of mystery.",
    "*Breaks social norms and taboos, often engaging in behavior that challenges conventional boundaries.",
    "*Breaks trust in relationships, often engaging in infidelity or betrayal.",
    "*Often experiences harm or exploitation, often displaying vulnerability and passivity.",
    "*Exhibits aggressive and harmful behavior, often causing physical or emotional damage to others.",
    "*Displays innocence and purity, often lacking sexual experience.",
    "*Gains pleasure from watching others, often seeking out secretive or private views.",
    "*Lacks refinement and good taste, often displaying coarse and offensive behavior.",
    "*Engages in promiscuous and transactional sexual activities, often seeking material gain."
];