const relationship = [
    "Acquaintance",
    "Aunt",
    "Best Friend",
    "Boss",
    "Boyfriend",
    "Brother",
    "Brother-in-law",
    "Child",
    "Colleague",
    "Cousin",
    "Daughter",
    "Daughter-in-law",
    "Father",
    "Father-in-law",
    "Fiancé",
    "Fiancée",
    "Friend",
    "Girlfriend",
    "Granddaughter",
    "Grandfather",
    "Grandmother",
    "Grandson",
    "Husband",
    "Lover",
    "Maid",
    "Mother",
    "Mother-in-law",
    "Nephew",
    "Niece",
    "Nurse",
    "Partner",
    "Patient",
    "Roommate",
    "Secretary",
    "Sister",
    "Sister-in-law",
    "Son",
    "Son-in-law",
    "Spouse",
    "Stepbrother",
    "Stepmother",
    "Stepfather",
    "Stepsister",
    "Stepson",
    "Stepdaughter",
    "Teacher",
    "Uncle",
    "Wife",
    //[NSFW]
    "Dominant",
    "Dominatrix",
    "Master",
    "Mistress",
    "Sex Worker",
    "Submissive"
];
const job = [
    "Actor",
    "Artist",
    "Baker",
    "Banker",
    "Bartender",
    "Chef",
    "Cleaner",
    "Coach",
    "Counselor",
    "Designer",
    "Doctor",
    "Driver",
    "Engineer",
    "Farmer",
    "Firefighter",
    "Gardener",
    "Lawyer",
    "Librarian",
    "Maid",
    "Mechanic",
    "Musician",
    "Nurse",
    "Painter",
    "Pharmacist",
    "Photographer",
    "Pilot",
    "Plumber",
    "Police Officer",
    "Professor",
    "Receptionist",
    "Secretary",
    "Software Developer",
    "Soldier",
    "Surgeon",
    "Teacher",
    "Technician",
    "Veterinarian",
    "Waiter",
    "Writer",
    //[NSFW]
    "*BDSM Performer",
    "*Cam Model",
    "*Dominatrix",
    "*Escort",
    "*Exotic Dancer",
    "*Fetish Model",
    "*Porn Act",
    "*Porn Actress",
    "*Phone Sex Operator",
    "*Sex Worker",
    "*Stripper",
    "*Sugar Baby",
    "*Webcam Performer"
];
const hobbies = [
    "Acting",
    "Baking",
    "Birdwatching",
    "Bowling",
    "Calligraphy",
    "Camping",
    "Chess",
    "Cooking",
    "Crafting",
    "Cycling",
    "Dancing",
    "Drawing",
    "Fishing",
    "Gardening",
    "Hiking",
    "Knitting",
    "Painting",
    "Photography",
    "Playing Musical Instruments",
    "Pottery",
    "Reading",
    "Rock Climbing",
    "Running",
    "Sculpting",
    "Sewing",
    "Singing",
    "Skiing",
    "Swimming",
    "Traveling",
    "Videography",
    "Volunteering",
    "Writing",
    "Yoga",
    //[NSFW]
    "*BDSM Play",
    "*Erotic Photography",
    "*Fetish Exploration",
    "*Kink Events Attendance",
    "*Masturbation",
    "*Online Adult Chatting",
    "*Pornography Viewing",
    "*Role-playing (Sexual)",
    "*Sexual Experimentation",
    "*Swinging",
    "*Watching Adult Films",
    "*Webcam Performances",
    "*Writing Erotica",
];
const clothing = [
    "Activewear",
    "Beachwear",
    "Business Casual",
    "Casual",
    "Cocktail Dress",
    "Evening Gown",
    "Formal Wear",
    "Jeans",
    "Office Wear",
    "Pajamas",
    "Party Dress",
    "Resort Wear",
    "Sportswear",
    "Streetwear",
    "Sundress",
    "Swimwear",
    "Traditional Wear",
    "Work Uniform",
    "Yoga Pants",
    //[NSFW]
    "*Bondage Gear",
    "*Costume Lingerie",
    "*Crotchless Panties",
    "*Erotic Costumes",
    "*Fishnet Stockings",
    "*Leather Harness",
    "*Lingerie",
    "*Nothing",
    "*Pasties",
    "*See-Through Clothes",
    "*Thigh-High Boots",
    "*Thongs"
];